### ISSUE TITLE
响应式网页设计实践

### ISSUE THREAD

**Issue by jkvim** [jkvim/jkvim.github.io#16]
# Responsive web design pratice

### type

- screen
- print

### query

- max-width 
  `@media (max-width: 1200px)` eq <= 1200px
- min-width
  `@media (min-width: 1200px)` eq >= 1200px

### and
  `@media (min-width: 768px) and (max-width: 1200px)` eq 768px <= screen <= 1200px

### taolu
  
1. Usually, default style is biggest size style
2. Then add media query style with descrease `max-witdh`
3. Last media query style will be the smallest screen size style

example

```css

body {
  width: 1200px;
}

@media (max-width: 1200px) {
  body {
    width: 900px;
  }
}

@media (max-width: 900px) {
  body {
    width: 720px;
  }
}
@media (max-width: 768px) {
  body {
    width: 480px;
  }
}

@media (max-width: 480px) {
  body {
    width: 320px;
  }
}

```
